### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by Lookyan** [Lookyan/netramesh#47]
Using routing enabled and WS gives us panic:
```
fatal error: concurrent map read and map write

goroutine 2855 [running]:
runtime.throw(0xa43119, 0x21)
        /usr/lib/go-1.12/src/runtime/panic.go:617 +0x72 fp=0xc001e83bd8 sp=0xc001e83ba8 pc=0x42d432
runtime.mapaccess1_faststr(0x9c46a0, 0xc001464900, 0xa3596d, 0xa, 0x0)
        /usr/lib/go-1.12/src/runtime/map_faststr.go:21 +0x464 fp=0xc001e83c48 sp=0xc001e83bd8 pc=0x4124a4
net/textproto.MIMEHeader.Get(0xc001464900, 0xa3596d, 0xa, 0x959be0, 0xc00047aed0)
        /usr/lib/go-1.12/src/net/textproto/header.go:35 +0x5d fp=0xc001e83c80 sp=0xc001e83c48 pc=0x63c0dd
github.com/Lookyan/netramesh/pkg/http.Header.Get(...)
        /go/src/github.com/Lookyan/netramesh/pkg/http/header.go:42
github.com/Lookyan/netramesh/pkg/protocol.(*NetHTTPRequest).fillSpan(0xc00026f680, 0xb01d80, 0xc00144a5a0, 0xc001ace500, 0x0)
        /go/src/github.com/Lookyan/netramesh/pkg/protocol/http.go:412 +0x3e1 fp=0xc001e83d78 sp=0xc001e83c80 pc=0x8fc7f1
github.com/Lookyan/netramesh/pkg/protocol.(*NetHTTPRequest).StopRequest(0xc00026f680)
        /go/src/github.com/Lookyan/netramesh/pkg/protocol/http.go:383 +0x16d fp=0xc001e83e00 sp=0xc001e83d78 pc=0x8fc1bd
github.com/Lookyan/netramesh/pkg/protocol.(*HTTPHandler).HandleResponse(0xc000116b60, 0xc000270740, 0xc000114218, 0xaf8f00, 0xc00026f680, 0x0)
        /go/src/github.com/Lookyan/netramesh/pkg/protocol/http.go:233 +0x980 fp=0xc001e83f60 sp=0xc001e83e00 pc=0x8faf50
github.com/Lookyan/netramesh/pkg/transport.HandleConnection.func1(0xaf4700, 0xc000116b60, 0xc000270740, 0xc000114218, 0xaf8f00, 0xc00026f680, 0xaf4700, 0xc00010a9f0)
        /go/src/github.com/Lookyan/netramesh/pkg/transport/handler.go:166 +0x62 fp=0xc001e83fa0 sp=0xc001e83f60 pc=0x8ffd52
runtime.goexit()
        /usr/lib/go-1.12/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001e83fa8 sp=0xc001e83fa0 pc=0x45b721
created by github.com/Lookyan/netramesh/pkg/transport.HandleConnection
        /go/src/github.com/Lookyan/netramesh/pkg/transport/handler.go:165 +0xb29
```

**Comment by Lookyan** [comment]
Fixed
